### ISSUE TITLE
Faster Numba script

### ISSUE THREAD

**Issue by mzy2240** [mdmaas/julia-numba#1]
Very interesting comparison! I really like it so I tried it my own. What I found is, if you improve the code a little bit and enable the fastmath option, you can see an approximate 10X speed up.
```python
@nb.jit(nopython=True, fastmath=True)   
def quad_trap(f,a,b,N):
    h = (b-a)/N
    integral = h * ( f(a) + f(b) ) / 2
    for k in range(N):
        xk = h * k + a
        integral += h*f(xk)
    return integral
```
I am using an Intel i9-9880H CPU with Numba version 0.55. The above script could finish quad_trap in 0.000028 seconds.
BTW, Numba also supports SIMD, so in your loop function you may want to have computations that can be run in parallel. I am not an expert on both Numba and Julia, but I am able to write a sparse matrix multiplication function in numba that is more than 5 times faster than scipy sparse.

**Comment by mdmaas** [comment]
Hi, thanks for sharing!

I absolutely forgot about compiler optimization flags! Thanks for pointing that out. I will check the results with fastmath and probably -O3 enabled in both Julia and Numba.

As for SIMD, the Numba documentation says something along the lines that support whatever is supported by LLVM, but I couldn't find any explicit reference on how to enforce it as I do with LoopVectorization.jl in Julia.

**Comment by mdmaas** [comment]
I just added the -fastmath flag as another test case in the post. This gives Numba almost a 2X advantage over IEEE-compliant math, but it is still 3X slower than Julia. It also doesn't affect the timings of the higher-order function.
